# Generated by Django 5.1.1 on 2024-10-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='プロフィール画像'),
        ),
    ]
