# Generated by Django 3.2.15 on 2022-08-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
