# Generated by Django 3.1 on 2021-12-10 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend_name',
        ),
        migrations.DeleteModel(
            name='talk_room',
        ),
        migrations.RemoveField(
            model_name='talkroom',
            name='myname',
        ),
        migrations.RemoveField(
            model_name='talkroom',
            name='yourname',
        ),
        migrations.AddField(
            model_name='talkroom',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talkroom',
            name='you',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='you', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talkroom',
            name='message',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
