# Generated by Django 4.2.1 on 2023-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=2048)),
                ('chat_content2', models.CharField(max_length=2048)),
                ('chat_content3', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Talk_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.IntegerField()),
                ('user_to', models.IntegerField()),
                ('chat_content', models.CharField(max_length=2048)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
