# Generated by Django 5.2.5 on 2025-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='e_mail',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default='password1234', max_length=28, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='password1234', max_length=28, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='unknownuser', max_length=40, verbose_name='名前'),
        ),
    ]
