# Generated by Django 4.2.7 on 2023-11-08 03:41

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

