# Generated by Django 5.1.6 on 2025-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_icon',
            field=models.ImageField(default='img/people-24px.svg', upload_to='user_icons', verbose_name='プロフィール画像'),
        ),
    ]
