# Generated by Django 4.2.1 on 2023-06-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('from_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_name', to=settings.AUTH_USER_MODEL)),
                ('to_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
