# Generated by Django 4.0.4 on 2022-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='createdTime',
            field=models.DateTimeField(),
        ),
    ]
