# Generated by Django 5.2.4 on 2025-09-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='talk',
            table='talk',
        ),
    ]
