# Generated by Django 4.2.1 on 2023-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='static/myapp/img/default_profile_img.jpg', upload_to=''),
        ),
    ]
