# Generated by Django 4.2.4 on 2023-09-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.IntegerField(verbose_name='受信者'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.IntegerField(verbose_name='送信者'),
        ),
    ]
