# Generated by Django 4.2.1 on 2023-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='view_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
