# Generated by Django 3.1 on 2022-05-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='time',
            new_name='sent_time',
        ),
    ]
