# Generated by Django 5.2.4 on 2025-08-07 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.CharField()),
            ],
        ),
    ]
