# Generated by Django 4.1.5 on 2023-02-02 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('talkroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.talkroommodel')),
            ],
        ),
    ]
