# Generated by Django 4.0.5 on 2022-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_chat',
            field=models.CharField(max_length=100),
        ),
    ]
