# Generated by Django 5.2.4 on 2025-08-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='talk',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_talks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_talks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
