# Generated by Django 4.2.7 on 2023-11-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
