# Generated by Django 4.2.1 on 2023-08-24 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to=settings.AUTH_USER_MODEL),
        ),
    ]
