# Generated by Django 4.2.1 on 2023-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
