# Generated by Django 4.0.4 on 2022-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='アイコン画像'),
        ),
    ]
