# Generated by Django 5.2.5 on 2025-09-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='receiver',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='talk',
            name='sender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
