# Generated by Django 4.2.1 on 2023-07-04 10:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to=''),
        ),
    ]
