# Generated by Django 4.2.2 on 2023-08-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_profile_img.jpg', upload_to='../media_local/'),
        ),
    ]
