# Generated by Django 4.2.4 on 2023-08-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_image_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_check',
            field=models.CharField(max_length=20, verbose_name='パスワード（確認用）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='ユーザー名'),
        ),
    ]
