# Generated by Django 4.2.1 on 2023-09-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_content_talk_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
