# Generated by Django 5.2.6 on 2025-09-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_passcode_user_passcode_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passcode_valid',
            new_name='is_verified',
        ),
    ]
