# Generated by Django 4.2.2 on 2023-06-29 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='image/noimage.png', upload_to='uploads', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
