# Generated by Django 5.2.4 on 2025-09-19 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_onetimepass_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='OneTimePass',
        ),
        migrations.CreateModel(
            name='OneTimePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
