# Generated by Django 4.2.2 on 2023-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_confirm',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
