# Generated by Django 4.2.1 on 2023-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_view_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.IntegerField()),
                ('user_to', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
