# Generated by Django 4.0.4 on 2022-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_custommessage_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
