# Generated by Django 5.2.4 on 2025-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_talk_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='myapp/static/img/noimage.png', upload_to='uploads', verbose_name='画像'),
        ),
    ]
