# Generated by Django 4.2 on 2023-05-29 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='talk',
            new_name='talk_content',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='time',
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
