# Generated by Django 5.1.6 on 2025-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_signup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='icon'),
        ),
    ]
