# Generated by Django 4.1.5 on 2023-02-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_talkroommodel_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='speaker',
            new_name='speaker_name',
        ),
    ]
