# Generated by Django 4.0.4 on 2022-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(default='default/default_user.png', upload_to='media/%Y/%m/%d/', verbose_name='アイコン画像'),
        ),
    ]
