# Generated by Django 5.2.4 on 2025-08-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='myapp_messa_sender__562971_idx',
            old_name='myapp_massa_sender__9fbdc5_idx',
        ),
    ]
