# Generated by Django 5.1.1 on 2024-10-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_message_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='talk',
        ),
    ]
