# Generated by Django 4.2 on 2023-05-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_talk_talk_talk_content_remove_talk_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_time',
            field=models.DateTimeField(),
        ),
    ]
