# Generated by Django 3.1 on 2022-01-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220104_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
