# Generated by Django 4.2.1 on 2023-06-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='view_date',
        ),
    ]
