# Generated by Django 4.0.4 on 2022-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='prof_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
