# Generated by Django 4.0.5 on 2022-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_talk_message_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='message',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
