# Generated by Django 4.2.1 on 2023-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_talk_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='default_img.png', upload_to=''),
        ),
    ]
