# Generated by Django 4.1.5 on 2023-02-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_speaker_messagemodel_speaker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='talkroom',
            new_name='talk_room',
        ),
    ]
