# Generated by Django 4.2.1 on 2023-09-07 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_talk_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='user',
        ),
        migrations.AddField(
            model_name='talk',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_talks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talk',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_talks', to=settings.AUTH_USER_MODEL),
        ),
    ]
