# Generated by Django 4.2.1 on 2023-08-24 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='送信内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信時刻')),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_send', to=settings.AUTH_USER_MODEL, verbose_name='送った人')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_received', to=settings.AUTH_USER_MODEL, verbose_name='もらった人')),
            ],
        ),
    ]
