# Generated by Django 5.2.4 on 2025-08-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_friendsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friendsData',
        ),
    ]
