# Generated by Django 4.0.4 on 2022-07-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_image_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='../../media/media/未設定.png', null=True, upload_to='media/', verbose_name='プロフィール画像'),
        ),
    ]
