# Generated by Django 5.2.5 on 2025-09-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_talk_receiver_alter_talk_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
    ]
