# Generated by Django 5.2.4 on 2025-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='/home/issei827/django_project2/intern_chat_app/myapp/static/myapp/img/noimage.png', upload_to='uploads', verbose_name='画像'),
        ),
    ]
