# Generated by Django 4.1.5 on 2023-02-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_talkroom_messagemodel_talk_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkroommodel',
            name='latest_message_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
