# Generated by Django 4.0.4 on 2022-05-25 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_myuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 6, 54, 328428, tzinfo=utc), verbose_name='date signed up'),
        ),
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat_content', models.CharField(max_length=1000)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_was_sent', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
