# Generated by Django 5.1.1 on 2024-10-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_message_message_talk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='time',
        ),
    ]
