# Generated by Django 4.0.4 on 2022-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommessage',
            name='receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='custommessage',
            name='sender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prof_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
