# Generated by Django 4.2.4 on 2023-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_talk_content_chat_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.IntegerField()),
                ('user_to', models.IntegerField()),
                ('chat_content', models.CharField(max_length=2048)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Talk_content',
        ),
    ]
