# Generated by Django 5.1.4 on 2025-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
