# Generated by Django 4.0.4 on 2022-05-30 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_myuser_pub_date_chatcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date signed up'),
        ),
    ]
