# Generated by Django 5.2.4 on 2025-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='images/noimage.png', upload_to='uploads', verbose_name='画像'),
        ),
    ]
