# Generated by Django 4.0.4 on 2022-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='..//media//media/未設定.png', null=True, upload_to='media/', verbose_name='プロフィール画像'),
        ),
    ]
