# Generated by Django 5.2.5 on 2025-09-01 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_talk_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='sender',
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
