# Generated by Django 4.1.5 on 2023-02-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_talkroommodel_latest_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
