# Generated by Django 4.0.4 on 2022-10-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default/light.png', upload_to='media/', verbose_name='アイコン画像'),
        ),
    ]
