# Generated by Django 4.2.2 on 2023-10-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
