# Generated by Django 4.0.4 on 2022-07-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_custommessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userTwoStepValificatoin',
            field=models.BooleanField(default=True),
        ),
    ]
