# Generated by Django 4.2.1 on 2023-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
