# Generated by Django 4.0.4 on 2022-10-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_myuser_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(default='default/default_user_icon.png', upload_to='media/%Y/%m/%d/', verbose_name='アイコン画像'),
        ),
    ]
