# Generated by Django 5.1.4 on 2025-03-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_talk_talk_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='talk',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='talk',
            name='recieve_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieve_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talk',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
