# Generated by Django 4.2.2 on 2023-09-21 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('message_date',), 'verbose_name_plural': 'Message'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='opposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
