# Generated by Django 4.2.1 on 2023-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='view_date',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
