# Generated by Django 4.1.5 on 2023-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_messagemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkroommodel',
            name='latest_message_content',
            field=models.TextField(null=True),
        ),
    ]
