# Generated by Django 5.1.6 on 2025-03-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_message_delete_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user2',
            field=models.IntegerField(),
        ),
    ]
