# Generated by Django 5.1.6 on 2025-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default='', max_length=30, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='', max_length=30, verbose_name='Password confirmation'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
