# Generated by Django 4.0.4 on 2022-07-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_usertwostepvalificatoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userTwoStepValificatoin',
            new_name='useTwoStepAuthentication',
        ),
    ]
