# Generated by Django 4.0.4 on 2022-07-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_usertwostepvalificatoin_customuser_usetwostepauthentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='useTwoStepAuthentication',
        ),
    ]
