# Generated by Django 5.1.6 on 2025-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_message_user1_alter_message_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
