# Generated by Django 4.2.1 on 2023-06-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_view_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='message',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='view_date',
        ),
    ]
