# Generated by Django 4.0.4 on 2022-10-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_myuser_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcontent',
            options={'verbose_name_plural': 'チャット内容'},
        ),
    ]
