# Generated by Django 4.1.5 on 2023-02-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_talkroommodel_latest_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='speaker_name',
            new_name='speaker_id',
        ),
    ]
