# Generated by Django 4.2.2 on 2023-10-12 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_from',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='send_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_to',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
