# Generated by Django 5.1.6 on 2025-03-06 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_password1_customuser_password2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(max_length=15, unique=True, verbose_name='fromuser')),
                ('touser', models.CharField(max_length=15, unique=True, verbose_name='touser')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Img'),
        ),
    ]
