# Generated by Django 4.2.1 on 2023-06-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_customuser_date_remove_customuser_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='time',
        ),
    ]
