# Generated by Django 5.1.6 on 2025-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_sended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_sended_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='icon'),
        ),
    ]
