# Generated by Django 4.0.4 on 2022-08-14 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_customuser_usetwostepauthentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommessage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='custommessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='custommessage',
            name='isReceipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custommessage',
            name='primeUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='msg', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommessage',
            name='subUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dummyMsg', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
