# Generated by Django 5.2.5 on 2025-09-01 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_talk_talk_from_alter_talk_talk_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='talk_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
