# Generated by Django 4.0.4 on 2022-10-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_chatcontent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcontent',
            options={'verbose_name': 'チャット内容', 'verbose_name_plural': 'チャット内容'},
        ),
    ]
