# Generated by Django 5.2.4 on 2025-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='content',
            field=models.CharField(max_length=512),
        ),
    ]
