# Generated by Django 3.1 on 2021-12-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210605_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
