# Generated by Django 5.1.6 on 2025-04-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_message_last_sended_at_alter_signup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='latest_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_message', to='myapp.message'),
        ),
    ]
