# Generated by Django 5.1.6 on 2025-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_talklog_fromuser_alter_talklog_touser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
