# Generated by Django 4.2.2 on 2023-10-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_to',
        ),
    ]
