# Generated by Django 5.1.6 on 2025-04-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_signup_latest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_sended_at',
        ),
        migrations.AlterField(
            model_name='signup',
            name='latest_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_latest_message', to='myapp.message'),
        ),
    ]
