# Generated by Django 5.1.6 on 2025-04-20 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talklog",
            name="fromuser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_talk",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="talklog",
            name="touser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_talk",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
