# Generated by Django 5.1.6 on 2025-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_message_last_sended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='ユーザーネーム'),
        ),
    ]
