# Generated by Django 5.1.6 on 2025-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
